sudo: required
services:
  - docker

before_install:
  - docker build -t zlyun1979/frontend -f Dockerfile.dev .

  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json

script:
  - docker run -e CI=true zlyun1979/frontend npm run test

after_success:
  - docker build -t zlyun1979/frontend .

  #login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #push image to docker hub
  - docker push zlyun1979/frontend